apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: helm
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: {{  .Values.myservice.port }}
  type: {{  .Values.myservice.type  }}
