apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-3
  namespace: helm
  labels:
    app: myapp-3
spec:
  replicas: {{   .Values.replicaCount   }}
  selector:
    matchLabels:
      app: myapp-3
  template:
    metadata:
      labels:
        app: myapp-3
    spec:
      containers:
      - name: myapp-3
        image: hashicorp/http-echo
        imagePullPolicy: Always
        args:
        - "-text=Helm-Deployment"
        ports:
        - containerPort: 5678
