apiVersion: apps/v1
kind: Deployment
metadata:
  name: Apache
  namespace: helm
  labels:
    app: Apache
spec:
  replicas: {{   .Values.replicaCount   }}
  selector:
    matchLabels:
      app: Apache
  template:
    metadata:
      labels:
        app: Apache
    spec:
      containers:
      - name: Apache
        image: httpd:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
