apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-2
  namespace: helm
  labels:
    app: myapp-2
spec:
  replicas: {{   .Values.replicaCount   }}
  selector:
    matchLabels:
      app: myapp-2
  template:
    metadata:
      labels:
        app: myapp-2
    spec:
      containers:
      - name: myapp-2
        image: hashicorp/http-echo
        imagePullPolicy: Always
        args:
        - "-text=Helm-Deployment"
        ports:
        - containerPort: 5678
