apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-2
  namespace: helm
spec:
  selector:
    matchLabels:
      app: myapp-2
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp-2
    spec:
      containers:
      - name: myapp
        image: hashicorp/http-echo
        args:
        - "-text=Sheetal-App1"
        ports:
        - containerPort: 5678
