apiVersion: v1
kind: Service
metadata:
  name: apache2-svc
  namespace: helm
spec:
  selector:
    app: apache2
  ports:
  - name: apache
    protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: {{  .Values.myservice.port }}
  type: {{  .Values.myservice.type  }}
